import { examplePing } from "./functions/example";
import { leadIntake } from "./functions/lead-intake";
import { jobStageChanged } from "./functions/job-stage";
import { dripRun } from "./functions/drip";
import { appointmentCalendarSync } from "./functions/appointment-calendar";
import { appointmentReminders } from "./functions/appointment-reminders";
import { dunningRun } from "./functions/dunning";
import { commissionOnPaid } from "./functions/commission";
import { referralFeeOnPaid } from "./functions/referral-fee";
import { qboPushInvoice, qboPushPayment } from "./functions/qbo-sync";
import { esignFinalize } from "./functions/esign-finalize";
import { roofrOrderMeasurement } from "./functions/roofr-order";
import { autoOrderMeasurementOnInspection } from "./functions/auto-order-measurement";
import { generateEstimateOnMeasurement } from "./functions/estimate-generate";
import { sendEstimateForSignature, estimateAcceptedAdvanceJob } from "./functions/estimate-sign";
import { createMaterialOrderOnAccepted } from "./functions/material-order";
import { meterUsageMonthly } from "./functions/meter-usage";
import { coldArchiveDocuments } from "./functions/cold-archive";
import { runReaper } from "./functions/run-reaper";
import { enrichmentSweep } from "./functions/enrichment-sweep";
import { taskHealthSweep } from "./functions/task-health-sweep";
import { opsDigest } from "./functions/ops-digest";
import { stormAlertDaily } from "./functions/storm-alert";
import { emailAppendSweep } from "./functions/email-append";
import { weatherReschedule } from "./functions/weather-reschedule";
import { changeOrderAccepted } from "./functions/change-order";
import { stormCertOnLead, stormCertOnLeadFailure } from "./functions/storm-cert";
import { leadRescore } from "./functions/lead-rescore";
import { leadCalibrationMonthly } from "./functions/lead-calibration";
import { leadSpeedToLead } from "./functions/lead-speed-to-lead";
import { leadCadence } from "./functions/lead-cadence";
import { voiceFallback } from "./functions/voice-fallback";
import { invoiceSentToBilling, invoicePaidToComplete } from "./functions/invoice-stage";
import { homeownerCrewNotify } from "./functions/homeowner-crew-notify";
import { homeownerDeliveryNotify } from "./functions/homeowner-delivery-notify";
import { retailCloseoutCadence } from "./functions/retail-cadence";
import { insuranceDepreciationDetect } from "./functions/depreciation-detect";
import { crewCheckedInToProduction, materialDeliveredToProduction, productionPhotosToCloseout } from "./functions/production-triggers";
import { homeownerNotify } from "./functions/homeowner-notify";
import { photoQc } from "./functions/photo-qc";
import { inspectionLiveBuild, inspectionFinalize } from "./functions/inspection-live-build";
import { inspectionNarrativeOnComplete } from "./functions/inspection-narrative";
import { repairCreditSweep } from "./functions/repair-credit-sweep";
import { relationshipCadenceSweep } from "./functions/relationship-cadence";
import { partnerAttributionSweep } from "./functions/partner-attribution-sweep";
import { partnerGradeRecompute } from "./functions/partner-grade-recompute";
import { certSlaSweep } from "./functions/cert-sla-sweep";
import { partnerQuarterlySweep } from "./functions/partner-quarterly-sweep";
import { blitzOnCrewScheduled } from "./functions/blitz-on-crew-scheduled";
import { stormBaselineWatch, stormReinspectSend } from "./functions/storm-reinspect-watch";
import { productionPhasesOnStage, productionPhaseQcReopen } from "./functions/production-phase-engine";
import { productionHoUpdate } from "./functions/production-ho-update";
import { productionEodWrap } from "./functions/production-eod-wrap";
import { productionBlockerStub } from "./functions/production-blocker";
import { productionDetectorSweep } from "./functions/production-detector-sweep";
import { fillSweep } from "./functions/fill-sweep";
import { valuationSnapshotMonthly } from "./functions/valuation-snapshot";
import { parseSupplierInvoice } from "./functions/supplier-invoice-parse";
import { priceGuardSupplierInvoice } from "./functions/supplier-invoice-guard";
import { canvassContractSigned } from "./functions/canvass-contract";
import { parseLeadDocument } from "./functions/parse-lead-document";
import { estimateOpenRace } from "./estimate-race";
import { estimateExpirySweep } from "./functions/estimate-expiry";
import { estimateVideoProcess } from "./functions/estimate-video-process";
import { ownerVideoDelivery } from "./functions/owner-video-delivery";
import { challengeSettleHourly } from "./functions/challenge-settle";
import { canvassSaleContractWatch } from "./functions/canvass-sale-watch";
import { canvassPingPrune } from "./functions/canvass-ping-prune";

export { inngest } from "./client";
export { examplePing } from "./functions/example";
export { leadIntake } from "./functions/lead-intake";
export { jobStageChanged } from "./functions/job-stage";
export { dripRun } from "./functions/drip";
export { appointmentCalendarSync } from "./functions/appointment-calendar";
export { appointmentReminders } from "./functions/appointment-reminders";
export { dunningRun } from "./functions/dunning";
export { commissionOnPaid } from "./functions/commission";
export { referralFeeOnPaid } from "./functions/referral-fee";
export { qboPushInvoice, qboPushPayment } from "./functions/qbo-sync";
export { esignFinalize } from "./functions/esign-finalize";
export { roofrOrderMeasurement } from "./functions/roofr-order";
export { autoOrderMeasurementOnInspection } from "./functions/auto-order-measurement";
export { generateEstimateOnMeasurement } from "./functions/estimate-generate";
export { sendEstimateForSignature, estimateAcceptedAdvanceJob } from "./functions/estimate-sign";
export { createMaterialOrderOnAccepted } from "./functions/material-order";
export { meterUsageMonthly } from "./functions/meter-usage";
export { coldArchiveDocuments } from "./functions/cold-archive";
export { runReaper } from "./functions/run-reaper";
export { enrichmentSweep } from "./functions/enrichment-sweep";
export { taskHealthSweep } from "./functions/task-health-sweep";
export { opsDigest } from "./functions/ops-digest";
export { stormAlertDaily } from "./functions/storm-alert";
export { sendTenantDigest } from "./ops-digest";
export { pageBreakGlass } from "./break-glass";
export { sweepTenantHealth, runCheck } from "./health-sweep";
export { sweepTenant, makeGeocodeEnricher, makeStormproofEnricher, ENRICHERS, type Enricher } from "./enrichment";
export { emailAppendSweep, appendEmailsForTenant } from "./functions/email-append";
export { weatherReschedule } from "./functions/weather-reschedule";
export { changeOrderAccepted } from "./functions/change-order";
export { draftChangeOrderScope } from "./functions/change-order-draft";
export { stormCertOnLead, stormCertOnLeadFailure } from "./functions/storm-cert";
export { leadRescore } from "./functions/lead-rescore";
export { leadCalibrationMonthly } from "./functions/lead-calibration";
export { leadSpeedToLead } from "./functions/lead-speed-to-lead";
export { leadCadence } from "./functions/lead-cadence";
export { voiceFallback } from "./functions/voice-fallback";
export { invoiceSentToBilling, invoicePaidToComplete } from "./functions/invoice-stage";
export { crewCheckedInToProduction, materialDeliveredToProduction, productionPhotosToCloseout } from "./functions/production-triggers";
export { homeownerCrewNotify } from "./functions/homeowner-crew-notify";
export { homeownerDeliveryNotify } from "./functions/homeowner-delivery-notify";
export { retailCloseoutCadence } from "./functions/retail-cadence";
export { insuranceDepreciationDetect } from "./functions/depreciation-detect";
export { homeownerNotify } from "./functions/homeowner-notify";
export { photoQc, runPhotoQc } from "./functions/photo-qc";
export { inspectionLiveBuild, inspectionFinalize, inspectionMediaHandler } from "./functions/inspection-live-build";
export { inspectionNarrativeOnComplete, draftInspectionNarrative, NARRATIVE_RUBRIC_V1, NARRATIVE_RUBRIC_KEY } from "./functions/inspection-narrative";
export { repairCreditSweep, sweepTenantRepairCredits, CREDIT_CHECKIN_TEMPLATE_KEY } from "./functions/repair-credit-sweep";
export { relationshipCadenceSweep, sweepTenantRelationshipCadence, RELATIONSHIP_TEMPLATE_KEYS } from "./functions/relationship-cadence";
export { partnerAttributionSweep } from "./functions/partner-attribution-sweep";
export { partnerGradeRecompute } from "./functions/partner-grade-recompute";
export { certSlaSweep } from "./functions/cert-sla-sweep";
export { partnerQuarterlySweep } from "./functions/partner-quarterly-sweep";
export { blitzOnCrewScheduled } from "./functions/blitz-on-crew-scheduled";
export { stormBaselineWatch, stormReinspectSend, sweepTenantStormBaselines, sendStormReinspectOutreach, STORM_OUTREACH_TEMPLATE_KEY } from "./functions/storm-reinspect-watch";
export { productionPhasesOnStage, productionPhaseQcReopen, instantiatePhasesHandler } from "./functions/production-phase-engine";
export { productionHoUpdate, sendPhaseCompleteUpdate, HO_UPDATE_RUBRIC_KEY, HO_UPDATE_RUBRIC_V1 } from "./functions/production-ho-update";
export { productionEodWrap, sendEodWrap } from "./functions/production-eod-wrap";
export { productionBlockerStub, draftBlockerChangeOrderStub } from "./functions/production-blocker";
export { productionDetectorSweep, sweepTenantProductionDetectors } from "./functions/production-detector-sweep";
export { fillSweep, sweepTenantFill } from "./functions/fill-sweep";
export { valuationSnapshotMonthly, snapshotTenantValuation } from "./functions/valuation-snapshot";
export { parseSupplierInvoice, parseSupplierInvoiceHandler } from "./functions/supplier-invoice-parse";
export { priceGuardSupplierInvoice, priceGuardHandler } from "./functions/supplier-invoice-guard";
export { getTenantSms } from "./telephony";
export { parsePriceSheet, type PriceSheetParseResult } from "./price-sheet-parse";
export { canvassContractSigned, storeCanvassContract, emailSignedCopy } from "./functions/canvass-contract";
export { parseLeadDocument, parseLeadDocumentHandler } from "./functions/parse-lead-document";
export { challengeSettleHourly } from "./functions/challenge-settle";
export { estimateOpenRace, raceNotify, raceResolve } from "./estimate-race";
export { answerEstimateQuestion } from "./estimate-qa";
export { estimateExpirySweep } from "./functions/estimate-expiry";
export { estimateVideoProcess } from "./functions/estimate-video-process";
export { ownerVideoDelivery, deliverOwnerVideos } from "./functions/owner-video-delivery";
export { canvassSaleContractWatch } from "./functions/canvass-sale-watch";
import type { InngestFunction } from "inngest";
// Explicit annotation: the inferred tuple type exceeds tsc's serialization limit (TS7056).
export const functions: InngestFunction.Any[] = [voiceFallback, examplePing, leadIntake, jobStageChanged, dripRun, appointmentCalendarSync, appointmentReminders, dunningRun, commissionOnPaid, referralFeeOnPaid, qboPushInvoice, qboPushPayment, esignFinalize, roofrOrderMeasurement, autoOrderMeasurementOnInspection, generateEstimateOnMeasurement, sendEstimateForSignature, estimateAcceptedAdvanceJob, createMaterialOrderOnAccepted, meterUsageMonthly, coldArchiveDocuments, runReaper, enrichmentSweep, taskHealthSweep, opsDigest, emailAppendSweep, changeOrderAccepted, stormCertOnLead, stormCertOnLeadFailure, leadRescore, leadCalibrationMonthly, leadSpeedToLead, leadCadence, invoiceSentToBilling, invoicePaidToComplete, crewCheckedInToProduction, materialDeliveredToProduction, productionPhotosToCloseout, homeownerCrewNotify, homeownerDeliveryNotify, retailCloseoutCadence, insuranceDepreciationDetect, weatherReschedule, homeownerNotify, photoQc, parseSupplierInvoice, priceGuardSupplierInvoice, canvassContractSigned, parseLeadDocument, stormAlertDaily, challengeSettleHourly, canvassSaleContractWatch, estimateOpenRace, estimateExpirySweep, estimateVideoProcess, ownerVideoDelivery, inspectionLiveBuild, inspectionFinalize, inspectionNarrativeOnComplete, repairCreditSweep, relationshipCadenceSweep, stormBaselineWatch, stormReinspectSend, productionPhasesOnStage, productionPhaseQcReopen, productionHoUpdate, productionEodWrap, productionBlockerStub, productionDetectorSweep, partnerAttributionSweep, partnerGradeRecompute, certSlaSweep, partnerQuarterlySweep, blitzOnCrewScheduled, fillSweep, valuationSnapshotMonthly, canvassPingPrune];
export { canvassPingPrune } from "./functions/canvass-ping-prune";
