/**
 * Shared test helpers — admin-connection row creation for isolation/setup.
 * Uses adminDb (RLS-bypass) so tests don't need an active tenant context
 * when bootstrapping fixtures. Each function returns the generated id(s).
 *
 * Uniqueness: the uuid generated by the DB is unique per call; we also
 * derive unique text values (emails, keys) from those uuids to avoid
 * collisions across re-runs against the persistent dev DB.
 */
import { adminDb } from "../src/admin-client.js";
import { tenant, user, customer, property, job, lead } from "../src/schema/index.js";

export async function makeTenant(): Promise<{ tenantId: string }> {
  const [t] = await adminDb
    .insert(tenant)
    .values({ name: "TestTenant", publicKey: `pk-${crypto.randomUUID()}`, clerkOrgId: `org-${crypto.randomUUID()}` })
    .returning();
  return { tenantId: t!.id };
}

export async function makeUser(tenantId: string): Promise<{ userId: string }> {
  const id = crypto.randomUUID();
  const [u] = await adminDb
    .insert(user)
    .values({ tenantId, name: "Test User", email: `user-${id}@test.example`, role: "rep" })
    .returning();
  return { userId: u!.id };
}

export async function makeJobWithCustomer(tenantId: string): Promise<{ jobId: string; customerId: string }> {
  const [c] = await adminDb
    .insert(customer)
    .values({ tenantId, name: "Test Customer" })
    .returning();
  const [p] = await adminDb
    .insert(property)
    .values({ tenantId, customerId: c!.id, address: "1 Test St" })
    .returning();
  const [j] = await adminDb
    .insert(job)
    .values({ tenantId, customerId: c!.id, propertyId: p!.id, type: "retail", stage: "lead" })
    .returning();
  return { jobId: j!.id, customerId: c!.id };
}

export async function makeLeadWithCustomer(tenantId: string): Promise<{ leadId: string; customerId: string }> {
  const [c] = await adminDb
    .insert(customer)
    .values({ tenantId, name: "Test Customer" })
    .returning();
  const [p] = await adminDb
    .insert(property)
    .values({ tenantId, customerId: c!.id, address: "1 Test St" })
    .returning();
  const [l] = await adminDb
    .insert(lead)
    .values({ tenantId, customerId: c!.id, propertyId: p!.id, source: "test" })
    .returning();
  return { leadId: l!.id, customerId: c!.id };
}

export async function makeLeadWithProperty(
  tenantId: string,
): Promise<{ leadId: string; customerId: string; propertyId: string }> {
  const [c] = await adminDb
    .insert(customer)
    .values({ tenantId, name: "Test Customer" })
    .returning();
  const [p] = await adminDb
    .insert(property)
    .values({ tenantId, customerId: c!.id, address: "1 Test St" })
    .returning();
  const [l] = await adminDb
    .insert(lead)
    .values({ tenantId, customerId: c!.id, propertyId: p!.id, source: "test" })
    .returning();
  return { leadId: l!.id, customerId: c!.id, propertyId: p!.id };
}

export async function makeJobWithProperty(tenantId: string): Promise<{ jobId: string; customerId: string; propertyId: string }> {
  const [c] = await adminDb
    .insert(customer)
    .values({ tenantId, name: "Test Customer" })
    .returning();
  const [p] = await adminDb
    .insert(property)
    .values({ tenantId, customerId: c!.id, address: "1 Test St" })
    .returning();
  const [j] = await adminDb
    .insert(job)
    .values({ tenantId, customerId: c!.id, propertyId: p!.id, type: "retail", stage: "lead" })
    .returning();
  return { jobId: j!.id, customerId: c!.id, propertyId: p!.id };
}
